### PR TITLE
Issue 75 istio ports

### PR DESCRIPTION
**Pull request by moxious**
- Rename port specifications on services and pods to conform to the recommended naming conventions for Istio

### CODE REVIEW

**Comment by mohammadsrahman** [comment]
@moxious you are awesome! When will you release?

**Comment by moxious** [comment]
@mohammadsrahman probably not yet, because this is the first PR since the last release.  But when I get the build to pass, you can go to the CI system and in the artifacts that the CI system produces, it will make for you a new tgz file that includes the new change. 

In the "checks" stage on this PR, you can go to CircleCI to see the build.  When it's green and the build passes (still working on it) you can then go to the "Artifacts" tab, and look for the `neo4j-(VERSION).tgz` file.  You can use this as a pre-release so you don't need to wait on the release itself.

(In order for this release to be generated though I have to get the build to pass.  ;)

**Comment by moxious** [comment]
@mohammadsrahman download available here: https://app.circleci.com/pipelines/github/neo4j-contrib/neo4j-helm/206/workflows/b96c7c6e-016a-4acd-a869-a65466977925/jobs/205/artifacts

Look for the file called build/neo4j-4.1.1-3.tgz

**Comment by mohammadsrahman** [comment]
> @mohammadsrahman download available here: https://app.circleci.com/pipelines/github/neo4j-contrib/neo4j-helm/206/workflows/b96c7c6e-016a-4acd-a869-a65466977925/jobs/205/artifacts
> 
> Look for the file called build/neo4j-4.1.1-3.tgz

Perfect thank you for the quick fixes. Not the first time either :)

**Pull request merged**
