### PR TITLE
fixes #104 run-time detection of namespace without helm

### LINKED ISSUE #104: Get the namespace at runtime for the core init scrips
Currently we use the namespace at template-creation time to modify the startup script of the core statefulsets and set the discovery advertised address.

You can get the namespace at runtime using `cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`

This line in the core startup command could be changed to make use of this:

```
export DISCOVERY_HOST="discovery-{{ template "neo4j.fullname" . }}-${core_idx}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
```

### PR DESCRIPTION
**Pull request by moxious**

### CODE REVIEW

**Comment by moxious** [comment]
@eastlondoner pretty sure this is what you had in mind -- but please provide LGTM or thumbs up and I'll merge.

**Comment by eastlondoner** [comment]
yes - should we do some testing?

**Comment by moxious** [comment]
@eastlondoner suggest something specific over and above "the cluster forms" and "all CI tests pass" which includes checking for services, data replication, etc. etc.

**Comment by eastlondoner** [comment]
cluster forms is good enough for me

**Comment by moxious** [comment]
I guess one hinky bit about this is whether this special magic mounted namespace file on Kubernetes is ever different, i.e. with older versions of kubernetes, distros for other clouds, etc. etc.

Interestingly, in an unrelated issue a user providing feedback made some points about helm being used for deterministic deploys, and relative to these comments, getting the value dynamically at runtime might not be desirable.  https://github.com/neo4j-contrib/neo4j-helm/issues/101#issuecomment-700000838

So perhaps a core question is how much commitment is made to helm, vs. how much we're ok with helm being used as a templating engine but not actively managing the release.

**Comment by eastlondoner** [comment]
yes, I am not anxious to rush this in.

**Pull request merged**
